name: metric

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  push: {branches: [main]}
  workflow_dispatch:

jobs:
  my-job:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Metrics embed
      uses: lowlighter/metrics@v3.16
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year # Display full year instead of half year
